version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  errcheck:
    check-type-assertions: true

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

#  revive:
#    rules:
#      - name: exported
#        disabled: true  # ✅ This actually disables it
#      - name: package-comments
#        disabled: true  # ✅ Disable package comment requirement too

  govet:
    enable:
      - shadow

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - misspell
    - gocritic
    - revive

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0